### ISSUE TITLE
What is self.EMA?

### ISSUE THREAD

**Issue by vishnu-m77** [vishnu-m77/DiffAPTOSC#20] opened 2023-11-28 20:38 UTC
This may be the root cause of all errors.

**Comment by Lakshay-G** [comment] 2023-12-12 03:17
No idea

**Comment by Lakshay-G** [comment] 2023-12-12 03:17
> This may be the root cause of all errors.

Maybe, but I don't know anything about it

**Comment by Sehmimul** [comment] 2023-12-13 16:38
I don't think this is the root cause of all the error, but this is certainly something that should have been answered and looked into when the issue was first made (i.e. 2 weeks ago). Basically EMA does this:

At each step of training we are updating all parameters (weights and biases). Let's just talk about 1 particular weight $\theta_{i}^{j}$ where $j$ represents the training iteration. Define $\theta_{i}^{0} = \alpha$ where $\alpha$ is random. Then say after $k$ steps of training you get a set $S_{k} = (\theta_{i}^{0}, \theta_{i}^{1}, ... \theta_{i}^{k})$. What EMA does is, in evaluation, it keeps track of the average weight (let's say average $p$ iterations). Then we will compute the average weight of the last $p$ weights of the set $S_{k}$ and use that in evaluation instead of using $\theta_{i}^{k}$ in evaluation. With this closing the issue and we will mention EMA as potential extension of current work.

More can be found here: https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage?version=stable

**Closed by Sehmimul** 2023-12-13 16:38 UTC
Labels: question
